"""
test_alpaca.py
unittesting for Alpaca
"""

import unittest
from alpaca import Alpaca
from alpaca import AlpacaError

class TestAlpaca(unittest.TestCase):
    def test_translate_error(self):
        self.assertRaises(AlpacaError, Alpaca.translate, ['*a+b]'])
    def test_translate(self):
        dot = Alpaca.translate(['(a|b)*abb'])
        self.assertEqual(dot.script,
            'digraph G {\n' +
            '    graph [rankdir = LR, label = "Generated by alpaca.py 1.0\\n(C) 2013 activesys.wb@gmail.com"];\n' +
            '    node [shape = circle];\n' +
            '    start [shape = plaintext, label = ""];\n' +
            '    start -> S0 [label = "start"];\n' +
            '    S4 [shape = doublecircle];\n' +
            '    S0 -> S1 [label = "a"];\n' +
            '    S0 -> S0 [label = "b"];\n' +
            '    S1 -> S1 [label = "a"];\n' +
            '    S1 -> S3 [label = "b"];\n' +
            '    S3 -> S1 [label = "a"];\n' +
            '    S3 -> S4 [label = "b"];\n' +
            '    S4 -> S1 [label = "a"];\n' +
            '    S4 -> S0 [label = "b"];\n' +
            '}')


