"""
test_dfa.py
unittesting for DFA
"""

import unittest
import copy
from graph import Graph
from dfa import DFA

class TestDFA(unittest.TestCase):
    def test_init_empty(self):
        self.dfa = DFA()
        self.assertEqual(self.dfa.graph, None)
    def test_init(self):
        g = Graph()
        g.new('a')
        self.dfa = DFA(copy.deepcopy(g))
        self.assertEqual(
            (self.dfa.graph.start, self.dfa.graph.finish, self.dfa.graph.adjlist), 
            (g.start, g.finish, g.adjlist))

    def test_minimize_only_one(self):
        g = Graph()
        g.new('a')
        self.dfa = DFA(copy.deepcopy(g))
        self.dfa.minimize()
        self.assertEqual((self.dfa.graph.start, self.dfa.graph.finish), (0, [1]))
        self.assertEqual(len(self.dfa.graph.adjlist), 2)
        self.assertEqual(len(self.dfa.graph.adjlist[0]), 1)
        self.assertIn((1, 'a'), self.dfa.graph.adjlist[0])
        self.assertEqual(len(self.dfa.graph.adjlist[1]), 0)
    def test_minimize_mindfa(self):
        g = Graph()
        g.adjlist.extend([[(1, 'a'), (0, 'b')], [(1, 'a'), (2, 'b')], [(1, 'a'), (3, 'b')], [(1, 'a'), (0, 'b')]])
        g.start = 0
        g.finish = [3]
        self.dfa = DFA(copy.deepcopy(g))
        self.dfa.minimize()
        self.assertEqual((self.dfa.graph.start, self.dfa.graph.finish), (0, [3]))
        self.assertEqual(len(self.dfa.graph.adjlist), 4)
        self.assertEqual(len(self.dfa.graph.adjlist[0]), 2)
        self.assertIn((1, 'a'), self.dfa.graph.adjlist[0])
        self.assertIn((0, 'b'), self.dfa.graph.adjlist[0])
        self.assertEqual(len(self.dfa.graph.adjlist[1]), 2)
        self.assertIn((1, 'a'), self.dfa.graph.adjlist[1])
        self.assertIn((2, 'b'), self.dfa.graph.adjlist[1])
        self.assertEqual(len(self.dfa.graph.adjlist[2]), 2)
        self.assertIn((1, 'a'), self.dfa.graph.adjlist[2])
        self.assertIn((3, 'b'), self.dfa.graph.adjlist[2])
        self.assertEqual(len(self.dfa.graph.adjlist[3]), 2)
        self.assertIn((1, 'a'), self.dfa.graph.adjlist[3])
        self.assertIn((0, 'b'), self.dfa.graph.adjlist[3])
    def test_minimize(self):
        g = Graph()
        g.adjlist.extend([[(1, 'a'), (2, 'b')], [(1, 'a'), (3, 'b')], [(1, 'a'), (2, 'b')], [(1, 'a'), (4, 'b')], [(1, 'a'), (2, 'b')]])
        g.start = 0
        g.finish = [4]
        self.dfa = DFA(copy.deepcopy(g))
        self.dfa.minimize()
        self.assertEqual((self.dfa.graph.start, self.dfa.graph.finish), (0, [4]))
        self.assertEqual(len(self.dfa.graph.adjlist), 5)
        self.assertEqual(len(self.dfa.graph.adjlist[0]), 2)
        self.assertIn((1, 'a'), self.dfa.graph.adjlist[0])
        self.assertIn((0, 'b'), self.dfa.graph.adjlist[0])
        self.assertEqual(len(self.dfa.graph.adjlist[1]), 2)
        self.assertIn((1, 'a'), self.dfa.graph.adjlist[1])
        self.assertIn((3, 'b'), self.dfa.graph.adjlist[1])
        self.assertEqual(len(self.dfa.graph.adjlist[2]), 1)
        self.assertIn((None, None), self.dfa.graph.adjlist[2])
        self.assertEqual(len(self.dfa.graph.adjlist[3]), 2)
        self.assertIn((1, 'a'), self.dfa.graph.adjlist[3])
        self.assertIn((4, 'b'), self.dfa.graph.adjlist[3])
        self.assertEqual(len(self.dfa.graph.adjlist[4]), 2)
        self.assertIn((1, 'a'), self.dfa.graph.adjlist[4])
        self.assertIn((0, 'b'), self.dfa.graph.adjlist[4])

    def test_transform(self):
        g = Graph()
        g.adjlist.extend([[(1, 'a'), (2, 'b')], [(1, 'a'), (3, 'b')], [(1, 'a'), (2, 'b')], [(1, 'a'), (4, 'b')], [(1, 'a'), (2, 'b')]])
        g.start = 0
        g.finish = [4]
        self.dfa = DFA(copy.deepcopy(g))
        self.dfa.minimize()
        dot = self.dfa.transform()
        self.assertEqual(dot.script,
            'digraph G {\n' +
            '    graph [rankdir = LR, label = "Generated by alpaca.py 1.0\\n(C) 2013 activesys.wb@gmail.com"];\n' +
            '    node [shape = circle];\n' +
            '    start [shape = plaintext, label = ""];\n' +
            '    start -> S0 [label = "start"];\n' +
            '    S4 [shape = doublecircle];\n' +
            '    S0 -> S1 [label = "a"];\n' +
            '    S0 -> S0 [label = "b"];\n' +
            '    S1 -> S1 [label = "a"];\n' +
            '    S1 -> S3 [label = "b"];\n' +
            '    S3 -> S1 [label = "a"];\n' +
            '    S3 -> S4 [label = "b"];\n' +
            '    S4 -> S1 [label = "a"];\n' +
            '    S4 -> S0 [label = "b"];\n' +
            '}')

